services:
  ptah:
    build:
      context: .
      args:
        PTAH_CONFIG_FILE: ptah_config.local.yaml
    ports:
      - "8001:8000"
    volumes:
      - ./:/app:Z
      - ./ptah_config.local.yaml:/opt/ptah_config.yaml:Z
    command: "--host :: --port 8001 --reload"
    env_file:
      - .env.local

    network_mode: host
