ptah_profiles:
  - name: ac2350
    openwrt_profile: 
      name: xiaomi_aiot-ac2350
      target: ath79
      arch: generic
      openwrt_version: 24.10.0
    packages:
      - '-luci'
      - 'curl'
      - 'libcurl'
    files:
      profile_shared_files:
        - name: ptah_files
          type: gitlab_release
          gitlab_release:
            release_path: /permalink/latest
            gitlab_url: https://gitlab.fai.rezel.net
            project_id: 129
            source:
              paths:
                - shared_files
                - ac2350
            credentials:
              token: GIT_PTAH_FILES_TOKEN
        - name: go_daemon
          type: gitlab_release
          gitlab_release:
            gitlab_url: https://gitlab.fai.rezel.net
            project_id: 27
            release_path: /permalink/latest
            assets:
              - name: hermes_daemon-linux-mips
                destination: /hermes_daemon
                permission: "774"
            source:
              paths:
                - ptah_files
            credentials:
              token: GIT_GO_DAEMON_TOKEN
      router_specific_files:
        - name: vault_ssl_mac
          type: vault_certificates
          vault_certificates:
            destination: /etc/ssl/certs
            pki_mount: core-dev
            pki_role: box-fai-rezel-net
            cn_suffix: .box.fai.rezel.net
            credentials:
              vault_token: K8S_VAULT_TOKEN
        - name: mac_jwt
          type: jwt_from_vault_transit
          jwt_from_vault_transit:
            destination: /etc
            transit_mount: transit
            transit_key: ptah-jwt-dev
            credentials:
              vault_token: K8S_VAULT_TOKEN
credentials:
  GIT_PTAH_FILES_TOKEN:
  GIT_GO_DAEMON_TOKEN:
  K8S_VAULT_TOKEN:
