ptah_profiles:
  - name: ac2350
    openwrt_profile: 
      name: xiaomi_aiot-ac2350
      target: ath79
      arch: generic
      openwrt_version: 24.10.0
    packages:
      - '-luci'
      - 'curl'
      - 'libcurl'
    files:
      profile_shared_files:
        - name: ptah_files
          type: gitlab_release
          gitlab_release:
            release_url: https://gitlab.com/api/v4/projects/499/releases/permalink/latest
            source:
              paths:
                - shared_files
                - ac2350
            credentials:
              token: GIT_TOKEN_1
        - name: go_daemon
          type: gitlab_release
          gitlab_release:
            release_url: https://gitlab.com/api/v4/projects/500/releases/permalink/latest
            assets:
              - name: hermes_daemon-linux-mips
                destination: /hermes_daemon
                permission: "774"
            source:
              paths:
                - ptah_files
            credentials:
              token: GIT_TOKEN_1
      router_specific_files:
        - name: vault_ssl_mac
          type: vault_certificates
          vault_certificates:
            destination: /etc/ssl/certs
            vault_server: https://vault.hashicorp.com
            pki_mount: core-dev
            pki_role: pki
            cn_suffix: .box.example.com
            credentials:
              token: VAULT_TOKEN_1
        - nam e: jwt_from_vault_secrets
          type: jwt_from_vault_secrets
          jwt_from_vault_secrets:
            destination: /etc
            vault_server: https://vault.hashicorp.com
            kv_mount: kv
            kv_path: ptah
            credentials:
              vault_token: VAULT_TOKEN_1
        
credentials:
  GIT_USER_1:
  GIT_TOKEN_1:
  VAULT_TOKEN_1:

global_settings:
  openwrt_base_releases_url: https://downloads.openwrt.org/releases
  openwrt_builder_file_ext: .Linux-x86_64.tar.zst
  git_repo_path: /opt/git
  routers_files_path: /opt/routers_files
  builders_path: /opt/builders
  output_path: /opt/output
  gitlab_releases_output_path: /opt/gitlab_releases
  router_temporary_path: /opt/temporary