---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptah-deployment
  namespace: ${DEPLOY_NAMESPACE}
  labels:
    app: ptah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptah
  template:
    metadata:
      labels:
        app: ptah
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role:
          "ptah_${DEPLOY_ENV}"
          # Writes at /vault/secrets/env
        vault.hashicorp.com/agent-inject-template-env: |
          {{ with secret "kv/data/ptah_${DEPLOY_ENV}" -}}
            GIT_PTAH_FILES_TOKEN="{{ .Data.data.git_ptah_files_token }}"
            GIT_GO_DAEMON_TOKEN="{{ .Data.data.git_go_daemon_token }}"
          {{- end }}
    spec:
      serviceAccountName: ptah-ksa
      containers:
        - name: ptah-container
          image: $PTAH_IMAGE_TAG
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.4"
              memory: "512Mi"
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
          env:
            - name: DEPLOY_ENV
              value: "${DEPLOY_ENV}"
            - name: VAULT_URL
              value: "https://vault.core.rezel.net"
            - name: VAULT_ROLE_NAME
              value: "ptah_${DEPLOY_ENV}"
      imagePullSecrets:
        - name: gitlab-registery-credentials
